In [26]:
#@title Базовый блок

#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [2]:
import numpy as np
np.random.seed(32)

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [11]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Как узнать объем памяти любого массива (★☆☆)

In [8]:
a.nbytes

80

#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [17]:
b = np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [25]:
c = b[::-1]
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [21]:
c = np.arange(0, 9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0] (★☆☆)

In [148]:
a = np.array([1,2,0,0,4,0])
indecies = a.nonzero()
print('Индексы ненулевых элементов:', list(indecies[0]))

Индексы ненулевых элементов: [0, 1, 4]


#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [151]:
a = np.random.rand(3,3,3)
a

array([[[0.27582469, 0.08827827, 0.68144934],
        [0.11974575, 0.77236631, 0.64895856],
        [0.64566561, 0.07341356, 0.39264328]],

       [[0.47919866, 0.96449778, 0.62169535],
        [0.57302012, 0.1309882 , 0.45181225],
        [0.41416445, 0.78370952, 0.12434764]],

       [[0.71216907, 0.40545287, 0.34378346],
        [0.41097336, 0.19698471, 0.0637664 ],
        [0.99198009, 0.60829764, 0.24573604]]])

#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [108]:
b = np.random.rand(10, 10)
print('Сгенерированный массив:\n', b)
print('Минимальное значение:', b.min())
print('Максимальное значение:', b.max())

Сгенерированный массив:
 [[0.65749209 0.19829948 0.4301017  0.89611687 0.01200627 0.90623954
  0.28401222 0.37849389 0.92588216 0.73214559]
 [0.76873358 0.59527199 0.45911047 0.28272938 0.75460944 0.57580093
  0.75182248 0.87985021 0.56259798 0.09806265]
 [0.30724683 0.43715892 0.00569461 0.05864699 0.56738242 0.43022561
  0.18252285 0.49862771 0.43282477 0.42983056]
 [0.2953104  0.56281604 0.76945988 0.44961989 0.66961609 0.52389209
  0.08590091 0.79038135 0.75203685 0.15570102]
 [0.28028508 0.9748739  0.82746057 0.85546659 0.93542169 0.59430225
  0.38148825 0.52220714 0.46988849 0.99014163]
 [0.53219468 0.29413407 0.20365279 0.07891042 0.38069866 0.99867257
  0.30912414 0.05690719 0.94561508 0.00907914]
 [0.0328278  0.32809486 0.17516768 0.79875106 0.45539771 0.21844968
  0.24733188 0.61930897 0.84869823 0.9219677 ]
 [0.39722415 0.12441986 0.94702026 0.74041095 0.64276847 0.42027392
  0.36274731 0.47630374 0.17806403 0.70907505]
 [0.48048685 0.29964716 0.16400242 0.33245068 0.0818359

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [217]:
c = np.random.rand(30)
print('Сгенерированный вектор:\n', c)
print('Среднее значение:', c.mean())

Сгенерированный вектор:
 [0.53163905 0.07160379 0.69149444 0.11708751 0.19351251 0.9123815
 0.31071241 0.3156425  0.80703011 0.40996057 0.51194336 0.1516063
 0.13435027 0.01545605 0.37901324 0.0966495  0.4421866  0.21666831
 0.82690236 0.67978573 0.26942989 0.95691278 0.98339226 0.29677764
 0.61948645 0.17089122 0.10164158 0.90304631 0.04905917 0.14577255]
Среднее значение: 0.41040119912512424


#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [272]:
a = np.array([[1, 0, 1], [1, 0, 1]])
a

array([[1, 0, 1],
       [1, 0, 1]])

#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

Решение: 
```python
np.nan 
False
False
np.nan
True
False
```

#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [211]:
a = np.arange(336).reshape(6, 7, 8)
cords = np.unravel_index(99,(6,7,8))
print(cords)

(1, 5, 3)


In [117]:
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [212]:
a[cords]

99

#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [123]:
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
c = np.dot(a,b)
c

array([[0.6915528 , 1.37769463],
       [0.16074061, 0.50738167],
       [0.84909459, 1.60571635],
       [0.71752225, 1.22934793],
       [0.75544123, 1.29247688]])

#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [235]:
np.random.seed(30)
a = np.random.randint(1, 11, size = (10))
print('Исходный массив:', a)

Исходный массив: [ 6  6  5  8  3  6  2  4 10  8]


In [236]:
#Находим индексы элементов, равных 3 и 8, меняем их местами 
a8 = np.where(a == 8)
a3 = np.where(a == 3)
a[a8] = 3
a[a3] = 8

In [237]:
print('Итоговый массив:', a)

Итоговый массив: [ 6  6  5  3  8  6  2  4 10  3]


#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

Решение: 
```python
nan
0
array([-2.14748365e+09])
```

#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [215]:
a = np.random.randint(1, 11, size = (10))
b = np.random.randint(1, 11, size = (10))
print('Сгенерированный массив a:', a)
print('Сгенерированный массив b:', b)
print('Пересечение массивов:', np.intersect1d(a, b))

Сгенерированный массив a: [ 3 10 10  4  1  9 10  3  2  6]
Сгенерированный массив b: [ 8 10  6  2  5  7  9  7  8  1]
Пересечение массивов: [ 1  2  6  9 10]


In [125]:
#@title Блок средней сложности

#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [264]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])
A = A*(-A/2) + B*(-A/2)
A

array([ -3.5,  -9. , -16.5, -26. , -37.5])

#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [327]:
#a = np.arange(0, 5).repeat(5).reshape(5,5)
a = np.array([np.arange(0, 5)] * 5)
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [265]:
a = np.linspace(0.0001, 0.9999, 10)
a

array([1.00000000e-04, 1.11188889e-01, 2.22277778e-01, 3.33366667e-01,
       4.44455556e-01, 5.55544444e-01, 6.66633333e-01, 7.77722222e-01,
       8.88811111e-01, 9.99900000e-01])

#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [270]:
a = np.random.rand(10)
print('Сгенерированный массив a:', a)
print('Отсортированный массив a:', np.sort(a))

Сгенерированный массив a: [0.51791651 0.62549818 0.33028383 0.10475525 0.64767021 0.26152518
 0.46585182 0.42562175 0.51911434 0.66818045]
Отсортированный массив a: [0.10475525 0.26152518 0.33028383 0.42562175 0.46585182 0.51791651
 0.51911434 0.62549818 0.64767021 0.66818045]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [185]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [190]:
from datetime import datetime
start_time = datetime.now()
np.sum(a)
print('Время на выполнение:', datetime.now() - start_time)

Время на выполнение: 0:00:00.000989


In [196]:
from datetime import datetime
start_time = datetime.now()
np.add.reduce(a)
print('Время на выполнение:', datetime.now() - start_time)

Время на выполнение: 0:00:00.001042


#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [5]:
A = np.random.rand(10)
B = np.random.rand(10)
print('Сгенерированный массив A:\n', A)
print('Сгенерированный массив B:\n', B)
if np.sum(A == B):
    print('Массивы равны')
else:
    print('Массивы не равны')
#или можно так  
equal = np.array_equal(A,B)
print(equal)

Сгенерированный массив A:
 [0.49403187 0.52412136 0.29854125 0.46310814 0.98478429 0.50113492
 0.39807245 0.72790532 0.86333097 0.02616954]
Сгенерированный массив B:
 [0.29001718 0.78906919 0.45711967 0.00692848 0.41933546 0.33067476
 0.60415213 0.32462084 0.98125108 0.58823195]
Массивы не равны
False


#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [305]:
a = np.random.rand(10)
print('Сгенерированный массив: \n', a)
a[a == a.max()] = 0
print('Измененный массив: \n', a)

Сгенерированный массив: 
 [0.7004652  0.48785223 0.09618029 0.90229279 0.20929077 0.47856844
 0.93527151 0.3702369  0.38911113 0.3370964 ]
Измененный массив: 
 [0.7004652  0.48785223 0.09618029 0.90229279 0.20929077 0.47856844
 0.         0.3702369  0.38911113 0.3370964 ]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [219]:
for dtype in [np.int8, np.int32, np.int64]:
    print(f'Минимальное представимое значение {dtype}: {np.iinfo(dtype).min}')
    print(f'Максимальное представимое значение {dtype}: {np.iinfo(dtype).max}\n')
for dtype in [np.float32, np.float64]:
    print(f'Минимальное представимое значение {dtype}: {np.finfo(dtype).min}')
    print(f'Максимальное представимое значение {dtype}: {np.finfo(dtype).max}\n')

Минимальное представимое значение <class 'numpy.int8'>: -128
Максимальное представимое значение <class 'numpy.int8'>: 127

Минимальное представимое значение <class 'numpy.int32'>: -2147483648
Максимальное представимое значение <class 'numpy.int32'>: 2147483647

Минимальное представимое значение <class 'numpy.int64'>: -9223372036854775808
Максимальное представимое значение <class 'numpy.int64'>: 9223372036854775807

Минимальное представимое значение <class 'numpy.float32'>: -3.4028234663852886e+38
Максимальное представимое значение <class 'numpy.float32'>: 3.4028234663852886e+38

Минимальное представимое значение <class 'numpy.float64'>: -1.7976931348623157e+308
Максимальное представимое значение <class 'numpy.float64'>: 1.7976931348623157e+308



#### 26. Как вывести все значения большого массива? (★★☆)

In [213]:
np.set_printoptions(threshold=np.inf)
a = np.arange(1001)
print(a)

[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
  196 

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [223]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.30248714 0.65580633 0.88137699 0.92718834 0.79117916
  0.32650775 0.42744282 1.19198272 0.73544118]
 [0.30248714 0.         0.37119089 0.61472876 0.64315887 0.49900352
  0.09303118 0.13799579 0.89001383 0.43794857]
 [0.65580633 0.37119089 0.         0.25173149 0.27265042 0.35708246
  0.41239611 0.31732651 0.6003934  0.28467553]
 [0.88137699 0.61472876 0.25173149 0.         0.11225121 0.50953687
  0.66305158 0.56893777 0.55606619 0.45599325]
 [0.92718834 0.64315887 0.27265042 0.11225121 0.         0.44234744
  0.67733985 0.5741595  0.44382955 0.40101763]
 [0.79117916 0.49900352 0.35708246 0.50953687 0.44234744 0.
  0.46645989 0.36462003 0.4284516  0.07546839]
 [0.32650775 0.09303118 0.41239611 0.66305158 0.67733985 0.46645989
  0.         0.11103618 0.87789186 0.41522032]
 [0.42744282 0.13799579 0.31732651 0.56893777 0.5741595  0.36462003
  0.11103618 0.         0.76873736 0.30827017]
 [1.19198272 0.89001383 0.6003934  0.55606619 0.44382955 0.4284516
  0.87789186 0.768737

#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [221]:
a = np.arange(15, dtype=np.float32)
a = a.astype(np.int32)
a.dtype

dtype('int32')

#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [334]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

a = np.genfromtxt(s, delimiter=",")
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [206]:
a = np.arange(1, 10).reshape(3,3)
print('Сгенерированный массив: \n', a)
means = a.mean(axis = 1)
for ind, m in enumerate(means):
    print(f'Среднее по {ind+1}-ой строке:', m)
    
result_matrix = a - means.reshape(3, 1)
print("Итоговая матрица:")
print(result_matrix.astype(int))

Сгенерированный массив: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Среднее по 1-ой строке: 2.0
Среднее по 2-ой строке: 5.0
Среднее по 3-ой строке: 8.0
Итоговая матрица:
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


In [173]:
#@title Блок повышенной сложности

#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [233]:
a = np.random.rand(10)
print("Сгенерированный вектор:\n", a)

ind = np.random.randint(0, len(a), 5)  
print("Индексы:\n", ind)

a[np.unique(ind)] += 1
print("Результирующий вектор:\n", a)

Сгенерированный вектор:
 [0.63499872 0.31557339 0.23321332 0.7276385  0.89033517 0.19181476
 0.05672678 0.18929901 0.18008722 0.18828261]
Индексы:
 [5 1 4 6 3]
Результирующий вектор:
 [0.63499872 1.31557339 0.23321332 1.7276385  1.89033517 1.19181476
 1.05672678 0.18929901 0.18008722 0.18828261]


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [269]:
import numpy as np

X = np.random.randint(1, 10, 10)
print("Вектор X:\n", X)

F = np.zeros((10, 10))
print("Исходный массив F:\n", F)

I = np.random.randint(0, len(F), 5)
print("Список индексов I:\n", I)

F[I] = X
print("Итоговый массив:\n", F)

Вектор X:
 [5 6 5 7 2 4 2 7 1 3]
Исходный массив F:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Список индексов I:
 [0 1 6 9 2]
Итоговый массив:
 [[5. 6. 5. 7. 2. 4. 2. 7. 1. 3.]
 [5. 6. 5. 7. 2. 4. 2. 7. 1. 3.]
 [5. 6. 5. 7. 2. 4. 2. 7. 1. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 6. 5. 7. 2. 4. 2. 7. 1. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [5. 6. 5. 7. 2. 4. 2. 7. 1. 3.]]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [207]:
a = np.random.randint(0, 10, size  = (1, 2, 3, 4))
print('Сгенерированный массив:\n', a)
sum_a = np.sum(a, axis=(2, 3))
print("Сумма по двум последним осям:")
print(sum_a)

Сгенерированный массив:
 [[[[3 0 3 2]
   [7 9 7 4]
   [8 8 9 5]]

  [[7 9 2 5]
   [5 3 6 1]
   [4 9 5 7]]]]
Сумма по двум последним осям:
[[65 63]]


#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [164]:
a = np.array([1, 2, 3, 4, 5])
a_new = (np.zeros(len(a) + (len(a)-1)*3)).astype(np.int8)
a_new[::4] = a
a_new

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5], dtype=int8)

#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [241]:
a = np.random.random((5,5,3))
print('Массив 5x5x3:\n', a)
b  = np.random.random((5,5))
print('Массив 5x5:\n', b)
b = b[:, :, np.newaxis]
print('Перемножение:\n', np.multiply(a, b))

Массив 5x5x3:
 [[[0.68933625 0.91546169 0.94375064]
  [0.70091147 0.34742289 0.67099249]
  [0.10323617 0.58618628 0.1142412 ]
  [0.0343286  0.24310464 0.70084383]
  [0.81031852 0.51410645 0.43325196]]

 [[0.83906482 0.21388838 0.01046992]
  [0.58319261 0.52263513 0.16326282]
  [0.89102748 0.08541244 0.24277499]
  [0.26745353 0.77708254 0.30804078]
  [0.85475134 0.20318167 0.49583643]]

 [[0.21088125 0.13046923 0.09953037]
  [0.69921217 0.7493222  0.30064918]
  [0.96926281 0.20505858 0.87331658]
  [0.0937412  0.10809628 0.22616303]
  [0.55082229 0.15014011 0.17523321]]

 [[0.88726803 0.41002481 0.97008968]
  [0.89358782 0.18521837 0.66939645]
  [0.09661818 0.92681054 0.91031443]
  [0.32638747 0.73334057 0.40089698]
  [0.51152413 0.01246806 0.02537038]]

 [[0.84064288 0.09516924 0.64485707]
  [0.73875898 0.33222522 0.09324467]
  [0.53121089 0.66491485 0.11273124]
  [0.17035763 0.53416498 0.23260088]
  [0.78682628 0.36946141 0.36039846]]]
Массив 5x5:
 [[0.51984684 0.84999278 0.45377342 0.

#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [282]:
def moving_average(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = np.arange(20)
moving_average(a, 3)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [289]:
Z = np.arange(1, 10)
print('Исходный массив:\n', Z)
print('Итоговый массив:\n', np.vstack([Z[i:i+3] for i in range(len(Z)-2)]))

Исходный массив:
 [1 2 3 4 5 6 7 8 9]
Итоговый массив:
 [[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [296]:
def distance(P0, P1, P):
    diff_P0_P = P0[:, np.newaxis, :] - P
    diff_P1_P = P1[:, np.newaxis, :] - P
    seg_lengths = np.linalg.norm(diff_P1_P - diff_P0_P, axis=2)
    cross_prod = np.cross(diff_P0_P, diff_P1_P, axis=2)
    distances = np.abs(cross_prod) / seg_lengths
    return distances

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[[ 4.69251709]
 [ 2.16801055]
 [ 0.13407965]
 [13.25872492]
 [ 0.0643094 ]
 [ 1.02011561]
 [ 3.00860381]
 [ 5.69048436]
 [ 1.69122544]
 [11.92573622]]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [291]:
Z = np.arange(1, 15)
R = np.reshape([Z[i:i+4] for i in range(11)], (11, 4))
print('Исходный массив:\n', Z)
print('Итоговый массив:\n', R)

Исходный массив:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Итоговый массив:
 [[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [335]:
a = np.random.randint(0, 10, size = (10))
np.linalg.matrix_rank(a)

1

#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [281]:
import numpy as np

a = np.random.randint(0, 10, 10)
print("Исходный массив:\n", a)

most = np.bincount(a).argmax()

most

Исходный массив:
 [4 5 7 2 7 8 6 7 6 2]


7

#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [246]:
A = np.random.randint(0, 10, (8,3))
B = np.random.randint(0, 10, (2,2))
print('Сгенерированный массив A:\n', A)
print('Сгенерированный массив B:\n', B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print('Строки:', rows)

Сгенерированный массив A:
 [[6 8 1]
 [7 6 0]
 [8 0 9]
 [9 4 0]
 [3 6 3]
 [5 7 1]
 [7 7 0]
 [1 9 1]]
Сгенерированный массив B:
 [[5 1]
 [1 9]]
Строки: [0 5 7]


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [175]:
a = np.random.randint(1, 15, size = (3,3))
b = np.random.randint(1, 15, size = (3,3))
print('Сгенерированный массив a:\n', a)
print('Сгенерированный массив b:\n', b)
print('Уникальные значения массивов:', np.unique(np.concatenate((a, b))))

Сгенерированный массив a:
 [[ 8 12 13]
 [14  7  4]
 [14 10 14]]
Сгенерированный массив b:
 [[ 9 10 11]
 [ 3  1  5]
 [ 8  7  7]]
Уникальные значения массивов: [ 1  3  4  5  7  8  9 10 11 12 13 14]
